[phases.setup]
nixPkgs = [
  'nodejs_20', 
  'python311',
  'python311Packages.pip',
  'python311Packages.fastapi',
  'python311Packages.uvicorn',
  'python311Packages.pydantic',
  'python311Packages.httpx',
  'python311Packages.python-dotenv',
  'python311Packages.tinydb'
]

[phases.install]
cmds = [
  'npm install',
  '/root/.nix-profile/bin/python3 -m pip install --user uvicorn[standard] fastapi python-dotenv tinydb'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'