[phases.setup]
nixPkgs = ['nodejs_20', 'python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = [
  'npm install',
  'python -m pip install --user --upgrade pip',
  'python -m pip install --user -r requirements.txt'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'